#pragma once

#include "LVPanel.h"
#include "LVContainer.h"
#include "LVLabel.h"
#include "LVButton.h"
#include "LVDropdown.h"
#include "LVTextarea.h"
#include "LVKeyboard.h"
#include "LVKeyboardNumeric.h"
#include "LVSwitch.h"
#include "LVCheckbox.h"
#include "LVFlexContainer.h"
#include "LVColor.h"
#include "fonts/lv_font_7seg_64.c"